# Generated by Django 5.2.4 on 2025-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
