# Generated by Django 5.2.4 on 2025-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rogatkalive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="smth",
            field=models.CharField(default="fff"),
            preserve_default=False,
        ),
    ]
