# Generated by Django 5.2.4 on 2025-07-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rogatkalive", "0002_user_smth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="smth",
        ),
    ]
